
services:
  db:
    build: ./db
    restart: always
    container_name: mysql-container
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_store:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_store:
    driver: local
  